# spring-boot-docker/docker-compose.yml
version: "3.9"
services:
  postgres-server:
    image: postgres:14
    ports:
      - "5432:5432"
    networks:
      - transaction-authorizer-network
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transaction
  transaction-authorizer-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
     OPENAI_API_KEY: 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
    networks:
      - transaction-authorizer-network
    depends_on:
      - postgres-server
networks:
  transaction-authorizer-network:
    driver: bridge